version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "50051:50051"
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=your_access_key
      - S3_SECRET_KEY=your_secret_key
      - S3_BUCKET=your_bucket_name
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "api/front.py"]
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
